language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

services:
  - mongodb

before_install:

before_script:
  # Set up Composer
  - composer self-update || true
  - composer install --prefer-dist
  # Set up permissions
  - chmod -R 777 app/var/

script:
  ## Default install tests
  # PHPUnit
  - phpunit -c phpunit.xml.dist


after_script:

# cache vendor dirs
cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR

