language: php

php:
  - 5.4
  - 5.5
  - 5.6
  # - 7.0 # because mongodb is not supported
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    #- php: 7.0 # because mongodb is not supported
    - php: hhvm

services:
  - mongodb

before_install:

before_script:
  # Set up PHP
  - if [[ $TRAVIS_PHP_VERSION =~ ^5 ]]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; fi
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'extension = mongo.so' >> /etc/hhvm/php.ini ; fi
  # Set up Composer
  - composer self-update || true
  - composer install --prefer-dist
  # Set up permissions
  - chmod -R 777 app/var/

script:
  ## Default install tests
  # PHPUnit
  - phpunit -c phpunit.xml.dist


after_script:

# cache vendor dirs
cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR

